stages:
  # - test
  - build
  - deploy

# test:
#   stage: test
#   script:
#     - npm install
#     - composer install
#     - composer update
#
build:
  stage: build
  script:
    - npm install
    - composer install

deploy:staging:
  stage: deploy
  environment:
    name: staging
    url: http://smallbizapi.devswebdev.com
  script:
  - ls
  - /home/gitlab-runner/vendor/bin/envoy run deploy-staging

deploy:production:
  stage: deploy
  environment:
    name: production
    url: http://smallbizcrm.com/packagemanager/public
  only:
  - master
  script:
  - /home/gitlab-runner/vendor/bin/envoy run deploy-production

  # - /home/gitlab-runner/.composer/vendor/bin/envoy run deploy-production
